FROM python:3.6.3-alpine3.6

RUN pip3 install --upgrade pip setuptools && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
    rm -r /root/.cache

RUN apk add --no-cache \
          gcc \
          musl-dev \
          hdf5

COPY requirements.txt /
RUN pip3 install --no-cache-dir -r requirements.txt

RUN python --version && \
    pip list --format=columns

WORKDIR /usr/src/app
VOLUME /usr/src/app

CMD ["python"]

# TODO mULTISTAGE with only python intallation!
